### ISSUE TITLE
Visual Studio 2022 Compatibility

### ISSUE THREAD

**Issue by KaterynaKateryna** [Predelnik/RemoveTrailingWhitespaces#2]
This extension is very useful, but I am finding that it doesn't appear to be compatible with Visual Studio 2022.
Are there any plans to update the project to work with 2022?

P.S.: This issue might look like a deja vu :)

**Comment by Predelnik** [comment]
It would be useful for me also, so there's a chance I would look into that.

**Comment by kevinramharak** [comment]
So I took a shot at trying to get a 2022 build working but I have very limited experience with building a Visual Studio extension.
I followed [this guide](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022) from Microsoft.

I ran in to the following issues:

## PackageReference
> Some assemblies that aren't unique to the Visual Studio SDK (for example, Newtonsoft.Json.dll) might have been discoverable through a simple <Reference Include="Newtonsoft.Json" /> reference before Visual Studio 2022. But in Visual Studio 2022, they require a package reference instead.

I installed these packages with Nuget and then used the [migration guide](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference) to move from `packages.config` to `PackageReference`. It took some effort but the build eventually worked out.

## `TextDocument.ReplacePattern`
[`TextDocument.ReplacePattern`](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/breaking-api-list?view=vs-2022#legacy-find-api-deprecation) is a deprecated API that will no longer work in VS 2022.
The extension uses the line:
```cs
textDocument.ReplacePattern("[^\\S\\r\\n]+(?=\\r?$)", "", (int)vsFindOptions.vsFindOptionsRegularExpression);
```
Which will have to be migrated to using the [`IFinder`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.operations.ifinder?view=visualstudiosdk-2019&preserve-view=true) and [`IFindService.CreateFinderFactory`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.operations.ifindservice.createfinderfactory?view=visualstudiosdk-2019&preserve-view=true) API's.

I don't have enough experience to figure out where to go from here, but I hope these findings help in updating the extension for VS 2022.

**Comment by mqcirrus** [comment]
I'd like to add that I'd also find VS2022 support useful.

**Comment by Predelnik** [comment]
Current progress: I've done most of the migration and it works on my machine but when I tried to install on other machine there was a problem with loading certain package it seems. I will try to resolve it, maybe migrating to `PackageReference` is actually that I need for this. It will be once again separate version for `2022` because supporting compatibility and testing on older versions would probably be too much for me.

**Comment by Predelnik** [comment]
And now this should work:
https://marketplace.visualstudio.com/items?itemName=Predelnik.RemoveTrailingWhitespaces-vs2022
As it turns out I was just using too new versions of the packages. Please report any issues with this version here or create new ones.
